spring:
  datasource:
#    c3p0:
#      jdbcUrl: jdbc:mysql://localhost:3306/tembin_money?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#      member: root
#      password: 417937
#      driverClass: com.mysql.jdbc.Driver
#      minPoolSize: 5
#      maxPoolSize: 60
#      maxIdleTime: 1800000
#      acquireIncrement: 5
#      maxStatements: 1000
#      initialPoolSize: 10
#      idleConnectionTestPeriod: 60
#      acquireRetryAttempts: 30
#      acquireRetryDelay: 1000
#      breakAfterAcquireFailure: false
#      testConnectionOnCheckout: false
    druid:
      url: ${datasource.url}
      username: ${datasource.member}
      password: ${datasource.password}
      driver-class-name: com.mysql.jdbc.Driver
      max-open-prepared-statements: 20
      initial-size: 10
      min-idle: 5
      max-active: 60
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j,config
      web-stat-filter:
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
        deny:
  jpa:
      database: mysql
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        use-new-id-generator-mappings: true
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl